server:
  port: 8080

spring:

  datasource:
    url: jdbc:h2:file:./db
    username: u
    password:

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
